# Generated by Django 3.1.7 on 2021-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_Board', models.CharField(max_length=2000)),
                ('appeared_boys', models.IntegerField()),
                ('appeared_girls', models.IntegerField()),
                ('appeared_total', models.IntegerField(blank=True)),
                ('passed_boys', models.IntegerField()),
                ('passed_girls', models.IntegerField()),
                ('passed_total', models.IntegerField(blank=True)),
                ('sc_appeared_boys', models.IntegerField()),
                ('sc_appeared_girls', models.IntegerField()),
                ('sc_appeared_total', models.IntegerField(blank=True)),
                ('sc_passed_boys', models.IntegerField()),
                ('sc_passed_girls', models.IntegerField()),
                ('sc_passed_total', models.IntegerField(blank=True)),
                ('st_appeared_boys', models.IntegerField()),
                ('st_appeared_girls', models.IntegerField()),
                ('st_appeared_total', models.IntegerField(blank=True)),
                ('st_passed_boys', models.IntegerField()),
                ('st_passed_girls', models.IntegerField()),
                ('st_passed_total', models.IntegerField(blank=True)),
            ],
        ),
    ]
